{
 "title": "SmartRetailX CloudWatch Observability Dashboard",
 "tags": [
  "cloudwatch",
  "smartretailx"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "SmartRetailX AWS EKS Infrastructure Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "EKS Worker Nodes CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "namespace": "ContainerInsights",
     "metricName": "node_cpu_utilization",
     "statistic": "Average",
     "dimensions": { "ClusterName": "smartretailx-eks-prod" },
     "region": "us-east-1"
    }
   ]
  },
  {
   "title": "EKS Worker Nodes Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "namespace": "ContainerInsights",
     "metricName": "node_memory_utilization",
     "statistic": "Average",
     "dimensions": { "ClusterName": "smartretailx-eks-prod" },
     "region": "us-east-1"
    }
   ]
  },
  {
   "title": "Database (RDS) & Cache (ElastiCache) Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "RDS PostgreSQL Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "namespace": "AWS/RDS",
     "metricName": "DatabaseConnections",
     "statistic": "Average",
     "dimensions": { "DBInstanceIdentifier": "prod-payments-db" },
     "region": "us-east-1"
    }
   ]
  },
  {
   "title": "RDS PostgreSQL CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "namespace": "AWS/RDS",
     "metricName": "CPUUtilization",
     "statistic": "Average",
     "dimensions": { "DBInstanceIdentifier": "prod-payments-db" },
     "region": "us-east-1"
    }
   ]
  },
  { "title": "AWS MSK Managed Kafka Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "AWS MSK Broker Bytes In / Bytes Out Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "namespace": "AWS/Kafka",
     "metricName": "BytesInPerSec",
     "statistic": "Sum",
     "dimensions": { "Cluster Name": "prod-kafka-broker" },
     "region": "us-east-1"
    },
    {
     "namespace": "AWS/Kafka",
     "metricName": "BytesOutPerSec",
     "statistic": "Sum",
     "dimensions": { "Cluster Name": "prod-kafka-broker" },
     "region": "us-east-1"
    }
   ]
  }
 ]
}